#
#  GRUB Makefile ending stub, to be automatically added to the end of the
#  part created by configure.
#

PROGS=	stage1 ffs_stage1_5 stage2 stage2_debug

all:
	@for X in $(PROGS) ; do (cd $$X ; $(MAKE)) ; done

clean:
	@for X in $(PROGS) ; do (cd $$X ; $(MAKE) clean) ; done
	rm -f config.log

