#
#  GRUB Makefile ending stub, to be automatically added to the end of the
#  part created by configure.
#

PROGS=	stage1 e2fs_stage1_5 fat_stage1_5 ffs_stage1_5 \
	stage2 stage2_debug

all:
	l="$(PROGS)"; for X in $$l; do (cd $$X && $(MAKE)) || exit 1; done

clean:
	l="$(PROGS)"; for X in $$l; do (cd $$X && $(MAKE) clean); done
	rm -f bin/*

distclean: clean
	rm -f Makefile config.log
