@node Memory map
@chapter Memory map


@node Embedded data
@chapter Embedded data


@node Filesystem interface
@chapter Filesystem interface


@node Bootstrap tricks
@chapter Bootstrap tricks


@node Memory detection
@chapter Memory detection


@node Low-level disk I/O
@chapter Low-level disk I/O


@node MBR
@chapter MBR


@node Partition table
@chapter Partition table
